name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run golangci-lint
        run: golangci-lint run ./...

  test:
    name: Run tests with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Run tests and enforce coverage
        run: |
          go test ./... -coverprofile=coverage.out -covermode=atomic
          go tool cover -func=coverage.out
          total=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage is $total%"
          if (( $(echo "$total < 85.0" | bc -l) )); then
            echo "Test coverage ($total%) is below 85%! ❌"
            exit 1
          fi
